// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTk2LyCCnHzJiNByJOC9d6l1JLTjkx8w',
    appId: '1:775380107022:web:3a3a0415f362b59475e15f',
    messagingSenderId: '775380107022',
    projectId: 'otakuverse-fafb8',
    authDomain: 'otakuverse-fafb8.firebaseapp.com',
    storageBucket: 'otakuverse-fafb8.firebasestorage.app',
    measurementId: 'G-Z3WK1BRQ9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsRvep1IF3P5JlktKNS_bI4geHbEb9KLQ',
    appId: '1:775380107022:android:cb141e1836317e4575e15f',
    messagingSenderId: '775380107022',
    projectId: 'otakuverse-fafb8',
    storageBucket: 'otakuverse-fafb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8bReXbcWtikAkauqMLpZ5W-KC8fNCT14',
    appId: '1:775380107022:ios:9a27f65943d7048875e15f',
    messagingSenderId: '775380107022',
    projectId: 'otakuverse-fafb8',
    storageBucket: 'otakuverse-fafb8.firebasestorage.app',
    iosBundleId: 'com.example.otakuverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8bReXbcWtikAkauqMLpZ5W-KC8fNCT14',
    appId: '1:775380107022:ios:9a27f65943d7048875e15f',
    messagingSenderId: '775380107022',
    projectId: 'otakuverse-fafb8',
    storageBucket: 'otakuverse-fafb8.firebasestorage.app',
    iosBundleId: 'com.example.otakuverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDTk2LyCCnHzJiNByJOC9d6l1JLTjkx8w',
    appId: '1:775380107022:web:6cf6913b43c5658d75e15f',
    messagingSenderId: '775380107022',
    projectId: 'otakuverse-fafb8',
    authDomain: 'otakuverse-fafb8.firebaseapp.com',
    storageBucket: 'otakuverse-fafb8.firebasestorage.app',
    measurementId: 'G-42GT0F6S3G',
  );
}