// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-dZ7TvAuNaeUUHoZ_bzK-_bQBGapjEOU',
    appId: '1:454205633639:web:e460ecb1343cae3a4150c2',
    messagingSenderId: '454205633639',
    projectId: 'otakuverse-12cbc',
    authDomain: 'otakuverse-12cbc.firebaseapp.com',
    storageBucket: 'otakuverse-12cbc.firebasestorage.app',
    measurementId: 'G-6J0QYSNVJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb3AGWMiEnSSHs5VOaAnK6fh1R3jXm36M',
    appId: '1:454205633639:android:9dbbe9ee517d78ec4150c2',
    messagingSenderId: '454205633639',
    projectId: 'otakuverse-12cbc',
    storageBucket: 'otakuverse-12cbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKKK0svGcit-GXtg-gYRg1c0J8lZBhqjI',
    appId: '1:454205633639:ios:f21efb4adb4d10b14150c2',
    messagingSenderId: '454205633639',
    projectId: 'otakuverse-12cbc',
    storageBucket: 'otakuverse-12cbc.firebasestorage.app',
    iosClientId: '454205633639-vgk2uvrkmmknqb2qbu51t27mrgl6eups.apps.googleusercontent.com',
    iosBundleId: 'com.mevcode.otakuverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKKK0svGcit-GXtg-gYRg1c0J8lZBhqjI',
    appId: '1:454205633639:ios:483a19a67ca824184150c2',
    messagingSenderId: '454205633639',
    projectId: 'otakuverse-12cbc',
    storageBucket: 'otakuverse-12cbc.firebasestorage.app',
    iosClientId: '454205633639-p7q3qo42r8g46mqndsolh38j1n8u0guh.apps.googleusercontent.com',
    iosBundleId: 'com.example.otakuverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-dZ7TvAuNaeUUHoZ_bzK-_bQBGapjEOU',
    appId: '1:454205633639:web:170ea3d88ef168b44150c2',
    messagingSenderId: '454205633639',
    projectId: 'otakuverse-12cbc',
    authDomain: 'otakuverse-12cbc.firebaseapp.com',
    storageBucket: 'otakuverse-12cbc.firebasestorage.app',
    measurementId: 'G-7KS64WFJTR',
  );

}